image: 
  file: .gitpod.Dockerfile

tasks:
  - before: >
      yes | sdk i java 8.0.232-open &&
      exit 0
  - init: >
      flutter upgrade &&
      flutter update-packages --force-upgrade &&
      flutter run -d web-server --no-resident

ports:
  - port: 8080
    onOpen: open-preview
