image: 
  file: .gitpod.Dockerfile

tasks:
  - before: >
      date &&
      yes | sdk i java 8.0.232-open
  - init: >
      date &&
      flutter channel beta &&
      flutter upgrade &&
      flutter config --enable-web &&
      flutter pub get
  - command: date

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.dart-code@3.5.0-beta.1:Wg2nTABftVR/Dry4tqeY1w==
    - Dart-Code.flutter@3.5.0:/kOacEWdiDRLyN/idUiM4A==
    - Nash.awesome-flutter-snippets@2.0.3:6jLJSOqEGV5k8R0xYG7Oqg==
