image: 
  file: .gitpod.Dockerfile

tasks:
  - before: >
      yes | sdk i java 8.0.232-open &&
      exit

vscode:
  extensions:
    - Dart-Code.dart-code@3.5.0-beta.1:Wg2nTABftVR/Dry4tqeY1w==
    - Dart-Code.flutter@3.5.0:/kOacEWdiDRLyN/idUiM4A==
    - Nash.awesome-flutter-snippets@2.0.3:6jLJSOqEGV5k8R0xYG7Oqg==
    - mathiasfrohlich.Kotlin@1.7.0:9xQZtwTUg4bdXHCMyxM7vQ==
    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
    - intellsmi.comment-translate@1.4.2:eTFMGnDqfEpALAFKi6xOSg==
    - naco-siren.gradle-language@0.2.3:zC8GEZcOCPVruGnbzEEMFQ==
